### ISSUE TITLE
New orthography profile – ELAN

### ISSUE THREAD

**Issue by cormacanderson** [cldf/orthograpy#1]
https://tla.mpi.nl/tools/tla-tools/elan/ipa-extension/

**Comment by cormacanderson** [comment]
Redirected from https://github.com/cldf/clts/issues/131

**Comment by xrotwang** [comment]
@cormacanderson Did you ever come across actual lexical data using the symbols on the left hand side as transcription alphabet? If so, I'd like to use them as a test case.

**Comment by cormacanderson** [comment]
It was actually @LudgerPaschen who put me on to this. I've never seen transcription data using it, but he might know...

**Comment by cormacanderson** [comment]
@LuPaschen rather

**Comment by LuPaschen** [comment]
Not sure the symbols are actually stored this way, it may be the case that they are converted on the fly to proper IPA symbols in ELAN. What I did see a few times was people using the input sequences in Praat ( http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__consonants.html , http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols.html ), which are only converted in the GUI but not in the actual TextGrids. I am afraid I myself do not have any files that could be used as a test case there, though.

**Comment by xrotwang** [comment]
Ah, ok. So if this is not something we might actually come across "in the wild", I close this issue.
